// Mirrors the backend WEBSOCKET_CLIENT_EVENTS
export const WEBSOCKET_CLIENT_EVENTS = {
  TRAFFIC_LOG: 'TRAFFIC_LOG',
  SECURITY_EVENT: 'SECURITY_EVENT',
  SYSTEM_STATUS: 'SYSTEM_STATUS',
  THREAT_NOTIFICATION: 'THREAT_NOTIFICATION',
} as const;
