export const SIEM_EVENT_TYPES = {
  AUTH_FAILURE: 'AUTH_FAILURE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  FINGERPRINT_MISMATCH: 'FINGERPRINT_MISMATCH',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
  REAUTH_FAILURE: 'REAUTH_FAILURE',
  THREAT_SCAN_FAILURE: 'THREAT_SCAN_FAILURE',
  THREAT_SCAN_TIMEOUT: 'THREAT_SCAN_TIMEOUT',
  MALICIOUS_BLOCKED: 'MALICIOUS_BLOCKED',
  RULE_MATCH: 'RULE_MATCH',
  SUSPICIOUS_PROCEED: 'SUSPICIOUS_PROCEED',
  PROXY_ERROR: 'PROXY_ERROR',
  VAULT_UNLOCKED: 'VAULT_UNLOCKED',
  VAULT_UNLOCK_FAILURE: 'VAULT_UNLOCK_FAILURE',
  VAULT_DECRYPT_FAILURE: 'VAULT_DECRYPT_FAILURE',
} as const;

export type SiemEventType =
  (typeof SIEM_EVENT_TYPES)[keyof typeof SIEM_EVENT_TYPES];

export const SIEM_EVENT_SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export type SiemEventSeverity =
  (typeof SIEM_EVENT_SEVERITIES)[keyof typeof SIEM_EVENT_SEVERITIES];

export const DEFAULT_EVENT_SEVERITIES: Record<SiemEventType, SiemEventSeverity> =
  {
    [SIEM_EVENT_TYPES.AUTH_FAILURE]: SIEM_EVENT_SEVERITIES.MEDIUM,
    [SIEM_EVENT_TYPES.SESSION_REVOKED]: SIEM_EVENT_SEVERITIES.MEDIUM,
    [SIEM_EVENT_TYPES.FINGERPRINT_MISMATCH]: SIEM_EVENT_SEVERITIES.HIGH,
    [SIEM_EVENT_TYPES.REAUTH_REQUIRED]: SIEM_EVENT_SEVERITIES.LOW,
    [SIEM_EVENT_TYPES.REAUTH_FAILURE]: SIEM_EVENT_SEVERITIES.MEDIUM,
    [SIEM_EVENT_TYPES.THREAT_SCAN_FAILURE]: SIEM_EVENT_SEVERITIES.CRITICAL,
    [SIEM_EVENT_TYPES.THREAT_SCAN_TIMEOUT]: SIEM_EVENT_SEVERITIES.CRITICAL,
    [SIEM_EVENT_TYPES.MALICIOUS_BLOCKED]: SIEM_EVENT_SEVERITIES.HIGH,
    [SIEM_EVENT_TYPES.RULE_MATCH]: SIEM_EVENT_SEVERITIES.MEDIUM,
    [SIEM_EVENT_TYPES.SUSPICIOUS_PROCEED]: SIEM_EVENT_SEVERITIES.HIGH,
    [SIEM_EVENT_TYPES.PROXY_ERROR]: SIEM_EVENT_SEVERITIES.CRITICAL,
    [SIEM_EVENT_TYPES.VAULT_UNLOCKED]: SIEM_EVENT_SEVERITIES.LOW,
    [SIEM_EVENT_TYPES.VAULT_UNLOCK_FAILURE]: SIEM_EVENT_SEVERITIES.MEDIUM,
    [SIEM_EVENT_TYPES.VAULT_DECRYPT_FAILURE]: SIEM_EVENT_SEVERITIES.HIGH,
  };

export const SIEM_EMIT_EVENTS = {
  TRAFFIC_LOG: 'TRAFFIC_LOG',
  SECURITY_EVENT: 'SECURITY_EVENT',
} as const;
