export const SIEM_EVENT_TYPES = {
  AUTH_FAILURE: 'AUTH_FAILURE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  FINGERPRINT_MISMATCH: 'FINGERPRINT_MISMATCH',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
  REAUTH_FAILURE: 'REAUTH_FAILURE',
  THREAT_SCAN_FAILURE: 'THREAT_SCAN_FAILURE',
  THREAT_SCAN_TIMEOUT: 'THREAT_SCAN_TIMEOUT',
  MALICIOUS_BLOCKED: 'MALICIOUS_BLOCKED',
  RULE_MATCH: 'RULE_MATCH',
  SUSPICIOUS_PROCEED: 'SUSPICIOUS_PROCEED',
  PROXY_ERROR: 'PROXY_ERROR',
  VAULT_UNLOCKED: 'VAULT_UNLOCKED',
  VAULT_UNLOCK_FAILURE: 'VAULT_UNLOCK_FAILURE',
  VAULT_DECRYPT_FAILURE: 'VAULT_DECRYPT_FAILURE',
  ANOMALY_DETECTED: 'ANOMALY_DETECTED',
} as const;

export type SiemEventType = (typeof SIEM_EVENT_TYPES)[keyof typeof SIEM_EVENT_TYPES];

export const SIEM_EVENT_SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export type SiemEventSeverity =
  (typeof SIEM_EVENT_SEVERITIES)[keyof typeof SIEM_EVENT_SEVERITIES];

// Mirrors backend SecurityEventPayload 
export interface SecurityEvent {
  id: string;
  type: SiemEventType;
  severity: SiemEventSeverity;
  message: string;
  createdAt: string;
  metadata?: Record<string, unknown>;
}
